I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day3.rpy", line 38, in script
    jump day_4
ScriptError: could not find label 'day_4'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day3.rpy", line 38, in script
    jump day_4
  File "C:\Users\dan03\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\dan03\Downloads\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'day_4'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090602
Любовь, деньги, шизофрения 
Fri Sep  9 13:03:06 2022
